services:
  - type: web
    name: staylodgify-backend
    runtime: docker
    repo: https://github.com/EricR19/staylodgifyBackend.git
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Jwt__Key
        generateValue: true
      - key: Jwt__Issuer
        value: StayLodgifyAPI
      - key: Jwt__Audience
        value: StayLodgifyClient
      - key: Jwt__ExpiresInMinutes
        value: 60
    healthCheckPath: /

